# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '5abf5033-815d-48ad-abcb-709344e9ad7a'
  imageRepository: 'bluegreen'
  containerRegistry: 'desattiracr.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '1023'

stages:

- stage: Deploy
  displayName: Deploy
  jobs:
    - job: Deploy
      displayName: Build
      pool: Hosted Ubuntu 1604
      
      steps:
      - task: KubernetesManifest@1
        name: bake
        inputs:
          action: 'bake'
          namespace: 'default'
          helmChart: 'charts/sampleapp'
          releaseName: 'bluegreen'
          overrides: |
            image.repository:$(containerRegistry)/bluegreen
            image.tag:$(tag)
            ingress.enabled:true
            ingress.hostname:bluegreen.d673faa123fa4d679d6c.eastus.aksapp.io

      - upload: '$(bake.manifestsBundle)'
          
      - task: KubernetesManifest@1
        inputs:
          action: 'deploy'
          kubernetesServiceConnection: 'desattir-bg'
          namespace: 'default'
          strategy: 'bluegreen'
          manifests: '$(bake.manifestsBundle)'
          imagePullSecrets: 'desattiracr'
